### ISSUE TITLE
Swift module not compatible with checking observation status

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_swift#10]
After installing `tom-swift`, when I run `manage.py updatestatus` to update the status of all my requested observations, I get this error:
```
Traceback (most recent call last):
  File "/var/www/saguaro_tom/manage.py", line 22, in <module>
    main()
  File "/var/www/saguaro_tom/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/tom_observations/management/commands/updatestatus.py", line 46, in handle
    failed_records[facility_name] = instance.update_all_observation_statuses(target=target)
AttributeError: 'SwiftFacility' object has no attribute 'update_all_observation_statuses'
```
Is the Swift ToO API able to retrieve observation statuses after they are requested? If so, it would be great to add this functionality. If not, we should at least make this not crash.

**Comment by phycodurus** [comment]
This specific issue is resolved with the stub implementation and the more general issue of the SwiftFacilty handling the Observations created is taken up in  #12
